{
    "squad": [
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z"
    ],
    "time": 7200,
    "vantage": 40,
    "derive": 3,
    "name": "Gara_1",
    "solutions_path": "C:\\Users\\miche\\MathScore\\Mathscore\\Pyscraper\\file.pdf",
    "data_old_path": "c:\\Users\\miche\\Mathscore\\Mathscore\\Pyscraper",
    "directory_recording": ":\\Users\\miche\\Mathscore\\Mathscore\\Pyscraper"
}
